package setupuri

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
)

// This file implements livesync's `?settingsQR=` payload, the format the
// plugin's own QR flow uses.
//
// Unlike the `?settings=` Setup URI it is NOT encrypted: the settings are packed
// into a positional array and encoded as text, so the CouchDB password and the
// E2EE passphrase are readable to anyone who scans or photographs the code. It
// exists because it needs no passphrase prompt on the receiving device.
//
// Both formats are consumed the same way. The plugin has no in-app camera - its
// "Scan QR Code" dialog only instructs the user to scan with the phone's camera
// app - so either QR is really just a carrier for an obsidian:// URL that the
// protocol handler picks up.
//
// The reference implementation is encodeAnyArray in
// octagonal-wheels/encoding/encodeobject.js and encodeSettingsToQRCodeData in
// livesync-commonlib/API/processSetting.js.

// configURIBaseQR is the prefix the plugin's protocol handler matches for the
// unencrypted payload.
const configURIBaseQR = "obsidian://setuplivesync?settingsQR="

// qrindex.json is generated by scripts/gen-template.mjs from the live
// KeyIndexOfSettings. It is positional: a stale copy would put values into the
// wrong settings, silently, so it is never hand-edited.
//
//go:embed qrindex.json
var qrIndexJSON []byte

var qrIndex struct {
	MaxIndex int `json:"maxIndex"`
	// Order preserves the reference object's key order, which decides the winner
	// when two keys map to the same slot.
	Order []struct {
		Key   string `json:"key"`
		Index int    `json:"index"`
	} `json:"order"`
}

func init() {
	if err := json.Unmarshal(qrIndexJSON, &qrIndex); err != nil {
		panic(fmt.Sprintf("setupuri: qrindex.json is not valid JSON: %v", err))
	}
	if qrIndex.MaxIndex <= 0 || len(qrIndex.Order) == 0 {
		panic("setupuri: qrindex.json is empty - run `make gen-template`")
	}
	present := make(map[string]bool, len(qrIndex.Order))
	for _, e := range qrIndex.Order {
		present[e.Key] = true
	}
	for _, key := range []string{"couchDB_URI", "couchDB_USER", "couchDB_PASSWORD", "couchDB_DBNAME", "passphrase"} {
		if !present[key] {
			panic(fmt.Sprintf("setupuri: qrindex.json has no slot for %q - run `make gen-template`", key))
		}
	}
}

// undefinedValue marks an array slot with no corresponding setting. JavaScript
// distinguishes undefined from null here and the encoding does too, so Go needs
// its own sentinel.
type undefinedValue struct{}

var jsUndefined = undefinedValue{}

// BuildQR returns the unencrypted `?settingsQR=` URI for a vault.
//
// Anyone who can see the QR gets the vault's CouchDB credentials and its
// end-to-end passphrase. Use Build instead where the code may be photographed,
// forwarded, or left on screen.
func BuildQR(cfg VaultConfig) (string, error) {
	settings, err := BuildSettings(cfg)
	if err != nil {
		return "", err
	}
	return EncodeQRURI(settings)
}

// EncodeQRURI packs a settings object into the `?settingsQR=` URI.
func EncodeQRURI(settings map[string]any) (string, error) {
	payload, err := encodeSettingsToQRCodeData(settings)
	if err != nil {
		return "", err
	}
	return configURIBaseQR + encodeURIComponent(payload), nil
}

// encodeSettingsToQRCodeData mirrors the function of the same name: build a
// dense array indexed by KeyIndexOfSettings, then encode it.
func encodeSettingsToQRCodeData(settings map[string]any) (string, error) {
	arr := make([]any, qrIndex.MaxIndex+1)
	for i := range arr {
		arr[i] = jsUndefined
	}

	// Assign every key in the reference order, absent ones included - they write
	// undefined. That matters because two keys currently share slot 64
	// (batchSave and batchSaveMinimumDelay), so the later one wins and can erase
	// a value the earlier one set. Skipping absent keys instead would keep
	// batchSave and produce a payload the plugin never generates.
	for _, e := range qrIndex.Order {
		v, ok := settings[e.Key]
		if !ok {
			v = jsUndefined
		}
		arr[e.Index] = v
	}

	return encodeAnyArray(arr, false)
}

// Prefix tables from encodeobject.js. Index is the length-of-length (1..5).
var (
	prefixString = [6]byte{0, 'V', 'W', 'X', 'Y', 'Z'}
	prefixObject = [6]byte{0, 'v', 'w', 'x', 'y', 'z'}
	prefixNumDec = [6]byte{0, 'a', 'b', 'c', 'd', 'e'} // "n": decimal
	prefixNumB36 = [6]byte{0, 'A', 'B', 'C', 'D', 'E'} // "N": base36
)

const (
	arrayMarker  = "_"
	objectMarker = "^"
)

// encodeAnyArray is the Go counterpart of encodeAnyArray(obj, safer).
func encodeAnyArray(values []any, safer bool) (string, error) {
	var b strings.Builder
	for _, v := range values {
		chunk, err := encodeValue(v, safer)
		if err != nil {
			return "", err
		}
		b.WriteString(chunk)
	}
	return b.String(), nil
}

func encodeValue(v any, safer bool) (string, error) {
	switch t := v.(type) {
	case undefinedValue:
		return "u", nil
	case nil:
		return "n", nil
	case bool:
		if t {
			return "t", nil
		}
		return "f", nil
	case json.Number:
		f, err := t.Float64()
		if err != nil {
			return "", fmt.Errorf("setupuri: number %q: %w", t, err)
		}
		return encodeNumber(f)
	case float64:
		return encodeNumber(t)
	case int:
		return encodeNumber(float64(t))
	case string:
		return encodeLengthPrefixed(prefixString, t)
	default:
		return encodeObject(v, safer)
	}
}

// encodeNumber mirrors the number branch: pick base36 when it is no longer than
// decimal, and always use decimal for non-integers.
func encodeNumber(f float64) (string, error) {
	isFloat := f != math.Trunc(f) || math.IsInf(f, 0) || math.IsNaN(f)
	decimal := jsNumberToString(f)

	expression := prefixNumDec
	encoded := decimal
	if !isFloat {
		base36 := strconv.FormatInt(int64(f), 36)
		if len(base36) <= len(decimal) {
			expression = prefixNumB36
			encoded = base36
		}
	}

	length := strconv.FormatInt(int64(len(encoded)), 36)
	if len(length) < 1 || len(length) > 5 {
		return "", fmt.Errorf("setupuri: number length %d is not encodable", len(encoded))
	}
	return string(expression[len(length)]) + length + encoded, nil
}

// encodeObject mirrors the object branch, which picks whichever of
// JSON.stringify and the recursive array form is shorter.
func encodeObject(v any, safer bool) (string, error) {
	jsonStr, err := jsStringify(v)
	if err != nil {
		return "", err
	}

	str := jsonStr
	if !safer {
		nested, err := encodeObjectAsArray(v)
		if err != nil {
			return "", err
		}
		if len(nested) < len(jsonStr) {
			str = nested
		}
	}
	return encodeLengthPrefixed(prefixObject, str)
}

// encodeObjectAsArray mirrors encodeObjectAsArray: arrays get "_", objects get
// "^" followed by their flattened key/value pairs.
func encodeObjectAsArray(v any) (string, error) {
	switch t := v.(type) {
	case []any:
		inner, err := encodeAnyArray(t, true)
		if err != nil {
			return "", err
		}
		return arrayMarker + inner, nil
	case map[string]any:
		// Key order must match jsStringify, which sorts, so that both branches
		// describe the same object.
		keys := sortedKeys(t)
		flat := make([]any, 0, len(keys)*2)
		for _, k := range keys {
			flat = append(flat, k, t[k])
		}
		inner, err := encodeAnyArray(flat, true)
		if err != nil {
			return "", err
		}
		return objectMarker + inner, nil
	default:
		return "", fmt.Errorf("setupuri: cannot encode %T in a QR payload", v)
	}
}

func encodeLengthPrefixed(prefixes [6]byte, s string) (string, error) {
	// JavaScript measures string length in UTF-16 code units, not bytes.
	length := strconv.FormatInt(int64(utf16Len(s)), 36)
	if len(length) < 1 || len(length) > 5 {
		return "", fmt.Errorf("setupuri: value of length %d exceeds the encodable maximum", utf16Len(s))
	}
	return string(prefixes[len(length)]) + length + s, nil
}

// utf16Len counts UTF-16 code units, matching JavaScript's String#length.
// Characters outside the BMP - emoji in a vault passphrase, say - count as two.
func utf16Len(s string) int {
	n := 0
	for _, r := range s {
		if r > 0xFFFF {
			n += 2
		} else {
			n++
		}
	}
	return n
}

// jsStringify renders a value the way JSON.stringify does.
//
// Go's encoding/json escapes <, > and & by default, which JSON.stringify does
// not, so HTML escaping is turned off. Map keys are sorted, which matches what
// the JavaScript side sees: it parses our settings from Go-marshalled JSON, and
// JSON.parse preserves that textual (sorted) order.
func jsStringify(v any) (string, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return "", fmt.Errorf("setupuri: stringify: %w", err)
	}
	return strings.TrimRight(buf.String(), "\n"), nil
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// jsNumberToString mirrors Number.prototype.toString() for the values that
// appear in livesync settings: small non-negative integers, occasionally a
// decimal. Exponential notation, which JavaScript formats differently from Go,
// is out of range for these settings; scripts/verify-setup-uri.mjs compares the
// full payload against the reference encoder and would catch it.
func jsNumberToString(f float64) string {
	if f == math.Trunc(f) && math.Abs(f) < 1e21 {
		return strconv.FormatFloat(f, 'f', -1, 64)
	}
	return strconv.FormatFloat(f, 'g', -1, 64)
}
