package setupuri

import (
	"bytes"
	"crypto/rand"
	_ "embed"
	"encoding/json"
	"fmt"
	"math/big"
	"strconv"
	"strings"
	"time"
)

// template.json is generated by scripts/gen-template.mjs from the official
// livesync library (`make gen-template`). It is the settings object the official
// Deno generator produces for a self-hosted CouchDB remote, already pruned by
// encodeSettingsToSetupURI's skipDefaultValue pass, with the five per-vault
// values left as placeholders.
//
// Regenerate it after bumping @vrtmrz/livesync-commonlib; the generator asserts
// that every placeholder survived pruning.
//
//go:embed template.json
var templateJSON []byte

// placeholders maps each template.json sentinel to the settings key that must
// carry it, kept byte-identical with scripts/gen-template.mjs. Checked at init
// so a regenerated template that renamed or dropped a key fails at startup
// rather than silently shipping a Setup URI with a literal "@@..." password.
var placeholders = map[string]string{
	"couchDB_URI":      "@@COUCHHUB_COUCHDB_URI@@",
	"couchDB_USER":     "@@COUCHHUB_COUCHDB_USER@@",
	"couchDB_PASSWORD": "@@COUCHHUB_COUCHDB_PASSWORD@@",
	"couchDB_DBNAME":   "@@COUCHHUB_COUCHDB_DBNAME@@",
	"passphrase":       "@@COUCHHUB_E2EE_PASSPHRASE@@",
}

const placeholderPrefix = "@@COUCHHUB_"

func init() {
	var tmpl map[string]any
	if err := json.Unmarshal(templateJSON, &tmpl); err != nil {
		panic(fmt.Sprintf("setupuri: template.json is not valid JSON: %v", err))
	}
	for key, token := range placeholders {
		if got, _ := tmpl[key].(string); got != token {
			panic(fmt.Sprintf("setupuri: template.json[%q] = %q, want %q - run `make gen-template`", key, got, token))
		}
	}
}

// VaultConfig is everything that varies per vault.
type VaultConfig struct {
	// CouchDBURI is the address Obsidian will talk to - the public one, reached
	// through the reverse proxy. It is deliberately not the address CouchHub
	// itself uses to administer the server.
	CouchDBURI string
	// User and Password are the vault's dedicated CouchDB account, not the
	// server admin.
	User     string
	Password string
	// DBName is the CouchDB database backing this vault.
	DBName string
	// E2EEPassphrase encrypts the vault contents at rest on the server. It must
	// differ from Password: the library's own documentation calls sharing them a
	// security failure, since the server operator would then hold both.
	E2EEPassphrase string
	// E2EEDisabled turns end-to-end encryption off in the issued settings.
	//
	// Only for adopting a database that is already storing plaintext: the
	// passphrase is what decrypts existing chunks, so it cannot be introduced
	// after the fact from here. An explicit flag rather than an empty
	// passphrase, so encryption is never dropped by omission.
	E2EEDisabled bool
}

func (c VaultConfig) validate() error {
	switch {
	case strings.TrimSpace(c.CouchDBURI) == "":
		return fmt.Errorf("setupuri: CouchDBURI is required")
	case c.User == "":
		return fmt.Errorf("setupuri: User is required")
	case c.Password == "":
		return fmt.Errorf("setupuri: Password is required")
	case c.DBName == "":
		return fmt.Errorf("setupuri: DBName is required")
	}

	if c.E2EEDisabled {
		if c.E2EEPassphrase != "" {
			return fmt.Errorf("setupuri: E2EEPassphrase must be empty when E2EEDisabled is set")
		}
		return nil
	}
	switch {
	case c.E2EEPassphrase == "":
		return fmt.Errorf("setupuri: E2EEPassphrase is required")
	case c.E2EEPassphrase == c.Password:
		return fmt.Errorf("setupuri: E2EEPassphrase must differ from the CouchDB password")
	}
	return nil
}

// BuildSettings produces the plaintext livesync settings object for a vault.
// Exported so tests and the cross-check tool can inspect it before encryption.
func BuildSettings(cfg VaultConfig) (map[string]any, error) {
	if err := cfg.validate(); err != nil {
		return nil, err
	}

	dec := json.NewDecoder(bytes.NewReader(templateJSON))
	dec.UseNumber() // keep 60 as "60" rather than round-tripping through float64
	var settings map[string]any
	if err := dec.Decode(&settings); err != nil {
		return nil, fmt.Errorf("setupuri: decode template: %w", err)
	}

	conn, err := serializeCouchDB(cfg.CouchDBURI, cfg.User, cfg.Password, cfg.DBName)
	if err != nil {
		return nil, err
	}

	// The plugin re-parses the connection string on import and overwrites these
	// four fields with what it recovers, so store the normalised URI rather than
	// the operator's raw input - otherwise the settings object disagrees with
	// itself about the address.
	settings["couchDB_URI"] = conn.NormalisedCouchDBURI
	settings["couchDB_USER"] = cfg.User
	settings["couchDB_PASSWORD"] = cfg.Password
	settings["couchDB_DBNAME"] = cfg.DBName
	settings["passphrase"] = cfg.E2EEPassphrase

	if cfg.E2EEDisabled {
		// The template turns both on. Path obfuscation hashes filenames with the
		// same passphrase, so it cannot stay on without one.
		settings["encrypt"] = false
		settings["usePathObfuscation"] = false
	}

	id, err := newRemoteConfigurationID()
	if err != nil {
		return nil, err
	}
	name := "CouchDB remote"
	if conn.Host != "" {
		name = "CouchDB " + conn.Host
	}
	settings["remoteConfigurations"] = map[string]any{
		id: map[string]any{
			"id":          id,
			"name":        name,
			"uri":         conn.URI,
			"isEncrypted": false,
		},
	}
	settings["activeConfigurationId"] = id

	// remoteType is deliberately absent: REMOTE_COUCHDB is "", which equals
	// DEFAULT_SETTINGS, so the official generator's skipDefaultValue pass strips
	// it. The plugin merges over DEFAULT_SETTINGS on import and recovers it.

	assertNoPlaceholders(settings)
	return settings, nil
}

// assertNoPlaceholders is a cheap guard against template.json gaining a new
// placeholder that BuildSettings does not fill in.
func assertNoPlaceholders(settings map[string]any) {
	for k, v := range settings {
		if s, ok := v.(string); ok && strings.HasPrefix(s, placeholderPrefix) {
			panic(fmt.Sprintf("setupuri: unfilled placeholder %s in setting %q - regenerate template or update BuildSettings", s, k))
		}
	}
}

// newRemoteConfigurationID mirrors createRemoteConfigurationId():
// `remote-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`.
func newRemoteConfigurationID() (string, error) {
	const alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"
	suffix := make([]byte, 6)
	for i := range suffix {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(alphabet))))
		if err != nil {
			return "", fmt.Errorf("setupuri: random id: %w", err)
		}
		suffix[i] = alphabet[n.Int64()]
	}
	return "remote-" + strconv.FormatInt(time.Now().UnixMilli(), 36) + "-" + string(suffix), nil
}
